spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mikemcd3912/EKSBlueprintsPipeline
    targetRevision: main
  ingress:
    host: prod.example.com