apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: frontend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/mikemcd3912/Unicorntrader
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: frontend
    helm:
      parameters:
      - name: spec.ingress.host
        value: {{ .Values.spec.ingress.host }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true